name: app
description: A sample command-line application.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.1
  github: ^9.14.0
  github_actions_toolkit: ^0.0.8
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
